# Generated by Django 5.0.6 on 2024-05-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
